### ISSUE TITLE
Adding External Heat Sources

### ISSUE THREAD

**Issue by nealkruis** [bigladder/hpwh-data-model#10]
We need to adapt heat source configuration to accept external heat sources (e.g., air-to-water heat pumps or [eventually] boilers). Here's a rough draft (but needs to be fleshed out more):

```yaml
ExternalHeatSource:
    heat_source:
        Data Type: (RSAIRTOWATERHEATPUMP, RSBOILER)
    pump: # Add in the future when pumps are separate representations
        Data Type: RSPUMP
    control_type:
        Data Type: <ExternalHeatSourceControlType> # Enumeration of FixedFlowRate (for multi-pass systems) or FixedOutletTemperature (for single-pass systems)
    fixed_flow_rate:
        Data Type: Numeric
        Units: m3/s
        Required: if control_type=FixedFlowRate
    fixed_outlet_temperature:
        Data Type: Numeric
        Units: K
        Required: if control_type=FixedOutletTemperature
```

Note: This data group does not represent a product directly (it is not a Representation Specification itself)--and does not have its own `Metadata` or `Description` data groups.
